### GET all blogs
GET http://localhost:3003/api/blogs

### GET one note by id

GET http://localhost:3003/api/blogs/67f0ea1327b3462ba1865f24


### UPDATE new note 

PUT http://localhost:3003/api/blogs/67dd420f901bd1b71b202d3c
Content-Type: application/json

{
    "title": "New blog",
    "author": "Henri Fantatik",
    "url": "https://somewhere.com",
    "likes": 13
}
###

### POST new
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "New blog",
    "author": "Henri Fantatik",
    "url": "https://somewhere.com",
    "likes": 0
}

### POST new note 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "I love life",
    "author": "Henri Fantatik",
    "url": "https://somewhere.com",
    "likes": 0
}

### DELETE blogpost
DELETE http://localhost:3003/api/blogs/67dd3c915ead5141ae808cf0


### POST new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "justmarijke",
    "name": "Marijke Lust",
    "password": "jageheimhoor"
}

### POST new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "henrifanatik",
    "name": "Henri Fanatik",
    "password": "secretsarefun"
}


### POST new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "marikonso",
    "name": "Mari Kondo",
    "password": "shinigama"
}

### POST login call - correct
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"henrifanatik",
    "password":"secretsarefun"
}

### POST new blog after login

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbnJpZmFuYXRpayIsImlkIjoiNjdkZjI0YjEwMjNkMTAwNDk0ZTJlM2VhIiwiaWF0IjoxNzQyNzQxODA1fQ.rh5tOr_57xdkh8SOpTzY5MZ69jLchlfRMes7GPX9x5Y


{
    "title": "Cleanup your soul & you house as well",
    "author": "Mari Kondo",
    "url":"https://mari-kondo.jp/love",
    "likes": 34
}

### POST login call - correct
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"marikonso",
    "password":"shinigama"
}


### POST login call - correct
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"justmarijke",
    "password":"jageheimhoor"
}

### POST login call - incorrect
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"justmarijke",
    "password":"jag"
}


### POST new blog after login

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmlrb25zbyIsImlkIjoiNjdlNjg4NGQyNTY4NmU0OTUyZWZiN2UyIiwiaWF0IjoxNzQzMTY0NDc0fQ.dEK2-Np_en5s0ltI5Y1Sxjka0vpwF8t4ZsDfHtLyALI


{
    "title": "Cleanup your life, now",
    "author": "Henri",
    "url":"https://the-truth.jp",
    "likes": 114
}


### POST new user broken
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hui",
    "name": "He",
    "password":"158587"
}

### DELETE call

DELETE http://localhost:3003/api/blogs/5a422b891b54a676234d17fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmlrb25zbyIsImlkIjoiNjdlNjg4NGQyNTY4NmU0OTUyZWZiN2UyIiwiaWF0IjoxNzQzMTY0NDc0fQ.dEK2-Np_en5s0ltI5Y1Sxjka0vpwF8t4ZsDfHtLyALI



### current request
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1c3RtYXJpamtlIiwiaWQiOiI2N2RlZDVjNzlkODNkOGQ4Y2EyMGE4OGYiLCJpYXQiOjE3NDM3NzkzMjF9.hUU4UY9bEsK8rRBRETe2oh9caipjYWCPUA2hjL_cwtg

{
    "title":"I am starting to like this",
    "author":"Naïma Oei",
    "url":"www.nederland.nl"
    }